### ISSUE TITLE
Broken with Unity 2017.2.0f3

### ISSUE THREAD

**Issue by Newbrict** [xioTechnologies/NGIMU-Unity-Example#1]
searching for devices no longer finds the devices

**Comment by Newbrict** [comment]
I think it may have something to do with the NgimuAPI.dll

**Comment by Newbrict** [comment]
I'm not sure if this is a unity issue or a searchforconnections issue now.... when I use the ngimu gui and search for connections while the unity demo is running I cannot find the UDP connection, as soon as I turn off the unity demo it shows up in the connection list.... inside unity I cannot see the udp connection at all though, but I could before upgrading unity... please advise

**Comment by xioTechnologies** [comment]
Only one application can use a UDP receive socket at a time.  If the Unity application is already running then it will be using the 'Search For Connections' UDP socket and therefore prevent the NGIMU GUI from using this socket.  Closing the Unity application releases the UDP socket.

The Unity was tested with Unity version 5.4.0f3.

**Comment by Newbrict** [comment]
I was seeing the connections show up in unity, but now they do not anymore, even though the ngimu gui is closed, I put debug statements in the discoveredconnection part of the code but it never hits... is there a way to debug this without compiling the dll myself?

**Comment by Newbrict** [comment]
Do you have an IRC channel or some way I can contact in real time so we can solve this please? Thank you....

**Comment by xioTechnologies** [comment]
The API source project is publicly available if you did want to compile the dll yourself:
https://github.com/xioTechnologies/NGIMU-Software-Public

We do not have an IRC channel.  I will contact you by email.
