### ISSUE TITLE
UWP Build Not working

### ISSUE THREAD

**Issue by GeorgeMichalakis** [xioTechnologies/NGIMU-Unity-Example#2]
I have a Hololens 1st gen device and trying to make it work with the NGIMU XIO unity example.
 
I switched platform to UWP, enabled every Capability and Supported Device Families in Project Settings, follow the appropriate settings for building via USB in Hololens in Visual Studio (x86-Device) however the app doesn't seem to work, as the Error State is being shown in Hololens when I open it.  

At first, it threw an Unsupported Exception regarding the Serialport.GetPortNames() method, however, even if surpass it by relying only on UDP connection (hololens doesn't have serial ports) and commenting out this.BeginSearchSerial() method which is inside the BeginSearch() method in the SearchForConnections.cs script (i.e rebuilding the NgimuApi dll), I still get the Error state.

I should add here, that in Unity's Editor (regarding Desktop Application), the WiFi connection isn't visible. 

Namely, if I run the Unity Editor without plugging in the ngimu xio, error state is being displayed, instead of the Wi-Fi connection or 0 devices found or something. The error state is the same as the one being encountered in UWP.
 Is it possible that there is a connection there?

Any thoughts of how should I proceed??

Thank you in advance.

**Comment by xioTechnologies** [comment]
The project was tested as described in the README.  We would not be able to test UWP any time soon.
