### ISSUE TITLE
problems with wifi communication unity-IMU

### ISSUE THREAD

**Issue by luciani1997** [xioTechnologies/NGIMU-Unity-Example#3]
Hi! I'm trying to use your Unity example to read data from an NGIMU connected via WiFi. It is connected to a tp-link router in client mode, and apparently, it all works correctly when running the Synchronised Network Manager application (my computer is connected to the same connection and I am able to correctly read data, also when trying other examples - like the one with Python). When running the Unity game you have uploaded, anyway, the system seems to be able to detect IMUs just when they are connected in serial mode. I have seen from the code that a ConnectionType variable exists: do I have to change its value to modify the type of connection that the game can detect? And if so, where can I modify it? Thank you!

**Comment by xioTechnologies** [comment]
The Unity example should work with Serial and Wi-Fi connections.  If only Wi-Fi connections are not working then this will likely be due to security or firewall settings on your machine blocking network connections.

**Comment by luciani1997** [comment]
ok, perfect! I deactivated the firewall for the private network I am using, and the system started correctly detecting the IMUs via WiFi. Thanks!
